camel.component.kafka.brokers=kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9091


topic=my-first-topic
broker=kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9091
topic.debezium=mysql.inventory.customers
